CREATE DATABASE billDb;
CREATE USER 'app'@'localhost' IDENTIFIED BY 'app';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON billDb.* TO 'app'@'localhost';