server {
  gzip                on;
  gzip_types          text/css application/json application/javascript;
  listen              80 default_server ipv6only=off;
  server_name         localhost;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # SPA fallback for Vue Router
    try_files $uri $uri/ /index.html?$args;
  }

  location /api/ {
    # trailing slash strips the /api prefix when proxying
    proxy_pass http://springboot:8080/;
  }

  error_page   500 502 503 504  /50x.html;
  location = /50x.html {
      root   /usr/share/nginx/html;
  }
}
